spring:
  application:
    name: Stack&Stock

  datasource:
    hikari:
      maximum-pool-size: 3

  devtools:
    restart:
      enabled: false

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true